# CFGNN to CFSQR
Create cfsqr style dataset for small amazon from cfgnn style data.

In [2]:
import pickle
import numpy as np
import torch

## CFSQR style data

In [3]:
with open("../datasets/Tree_Grids/syn_data.pkl", "rb") as file:
    tg = pickle.load(file)

# * Change according to need.
path = "/home/graphAttack/armagaan/code/rough/small_amazon/small_amazon.pickle"
with open(path, "rb") as file:
    sa = pickle.load(file)

In [4]:
tg

(array([[0., 1., 1., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 1., 0., 1.],
        [0., 0., 0., ..., 0., 1., 0.]], dtype=float32),
 array([[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]], dtype=float32),
 array([[1, 0],
        [1, 0],
        [1, 0],
        ...,
        [0, 1],
        [0, 1],
        [0, 1]]),
 array([[0., 1., 1., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 1., 0., 1.],
        [0., 0., 0., ..., 0., 1., 0.]], dtype=float32))

In [5]:
for i in tg:
    print(i.shape)

(1231, 1231)
(1231, 10)
(1231, 2)
(1231, 1231)


## New dataset

In [6]:
for key, val in sa.items():
    try:
        print(key, type(val), val.shape)
    except:
        print(key, type(val), len(val))

adj <class 'numpy.ndarray'> (1, 7650, 7650)
feat <class 'numpy.ndarray'> (1, 7650, 745)
labels <class 'list'> 7650
train_idx <class 'list'> 305
test_idx <class 'list'> 300


In [7]:
new_adj = sa["adj"][0]
new_feat = sa["feat"][0]
new_edge_labels = sa["adj"][0]

In [8]:
classes = 1 + torch.tensor(sa["labels"]).max().item()
new_labels = np.zeros((new_adj.shape[0], classes)).astype(int)

In [9]:
for i, label in enumerate(sa["labels"]):
    new_labels[i, label] = 1

In [10]:
new_data = (new_adj, new_feat, new_labels, new_edge_labels)

In [11]:
new_data

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 1.],
        ...,
        [0., 1., 0., ..., 0., 0., 0.],
        [1., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.]], dtype=float32),
 array([[0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 1, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float

In [12]:
path = "../datasets/small_amazon/" # Change according to need
with open(f"{path}/syn_data.pkl", "wb") as file:
    pickle.dump(new_data, file)

In [15]:
# Change according to need
with open(f"../datasets/Eval-sets/eval-set-small_amazon.pkl", "wb") as file:
    pickle.dump(sa["test_idx"], file)